package io.testproject.generated.tests.myfirstproject;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.AndroidDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.AndroidTest;
import io.testproject.java.sdk.v2.tests.helpers.AndroidTestHelper;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: My first Project
 * Test: TestSimonWrong
 * Generated by: B deBautista (fsimonbcontact@gmail.com)
 * Generated on Wed Jul 06 23:55:42 GMT 2022.
 */
@Test(
    name = "TestSimonWrong",
    version = "1.0"
)
public class Testsimonwrong implements AndroidTest {
  public ExecutionResult execute(AndroidTestHelper helper) throws FailureException {
    AndroidDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;

    // 1. Reset App
    //    Clear application data and restart (Auto-generated)
    GeneratedUtils.sleep(500);
    booleanResult = driver.testproject().resetApp();
    report.step("Reset App", booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Click '8'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_8_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click '8'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Click 'dividir'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_div_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'dividir'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Click '0'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_0_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click '0'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Click 'igual a'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_equal_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'igual a'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Does '= No se puede dividir entre cero' contain '= No se puede dividir entre cero'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//android.widget.TextView[@text = '= No se puede dividir entre cero']");
    booleanResult = driver.testproject().containsText(by,"= No se puede dividir entre cero");
    report.step("Does '= No se puede dividir entre cero' contain '= No se puede dividir entre cero'?", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Click 'borrar'
    GeneratedUtils.sleep(500);
    by = By.id("com.miui.calculator:id/btn_c_s");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'borrar'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
